### ISSUE TITLE
unexpected output during activation

### ISSUE THREAD

**Issue by luizbills** [julieeeeeee/no-wp-admin#5]
unexpected output during activation
![image](https://user-images.githubusercontent.com/1798830/35544250-93edc3f8-0550-11e8-8213-de4385ffdff3.png)

PS: very nice admin theme :+1:

**Comment by jiyooooon** [comment]
aw thank you! yes, i'm aware of this issue and will fix soon! :))

**Comment by luizbills** [comment]
other notices

![image](https://user-images.githubusercontent.com/1798830/35586076-ebf8b6e4-05e0-11e8-9787-fdaac422e5ef.png)

**Comment by jiyooooon** [comment]
Got it - thanks! I should have time tomorrow and start trying to fix these issues. Would you like to contribute to this project? I am new to github and don't know how to add you to the project!

**Comment by luizbills** [comment]
I'd like to help of course. But you do not need to put me as a collaborator. When I have a time I will send some pull request and then you review them.

**Comment by jiyooooon** [comment]
Awesome!
