### ISSUE TITLE
some design suggestions

### ISSUE THREAD

**Issue by luizbills** [julieeeeeee/no-wp-admin#8]
- remove `box-shadow` of inputs, selects, checkboxes, dashboard panels, secundary buttons...
- change `padding` of inputs and selects to `8px 12px`
- change `box-shadow` of admin notice to `0 0px 1px 0px rgba(0,0,0,.1)`
- change default red color of admin notice to `#FF6C5C`

![image](https://user-images.githubusercontent.com/1798830/35585811-1de910fa-05e0-11e8-93b9-e78c0a062ddf.png)

**Comment by jiyooooon** [comment]
great suggestions - will add in soon
